/*
Skycons is a set of ten animated weather glyphs, procedurally generated by JavaScript using the HTML5 canvas tag.
http://darkskyapp.github.io/skycons/
*/
var skycons = new Skycons();
  // on Android, a nasty hack is needed: {"resizeClear": true}

  // you can add a canvas by it's ID...
  skycons.add("today", Skycons.PARTLY_CLOUDY_DAY);
  skycons.add("day1", Skycons.CLEAR_DAY);
  skycons.add("day2", Skycons.CLOUDY);
  skycons.add("day3", Skycons.RAIN);

  // start animation!
  skycons.play();
  
  // want to change the icon? no problem:
  //skycons.set("today", Skycons.PARTLY_CLOUDY_NIGHT);

  
var citiesChinese = ["臺北市","新北市","台中市","臺南市","高雄市","基隆市","桃園市","新竹市","新竹縣","苗栗縣","彰化縣","南投縣","雲林縣","嘉義市", "嘉義縣", "屏東縣", "宜蘭縣", "花蓮縣", "台東縣", "澎湖縣", "金門縣", "連江縣"];  
var citiesEnglish = ["Taipei City", "New Taipei City", "Taichung City", "Tainan City", "Kaohsiung City", "Keelung City", "Taoyuan City", "Hsinchu City", "Hsinchu County", "Miaoli County", "Changhua County", "Nantou County", "Yunlin County", "Chiayi City", "Chiayi County", "Pingtung County", "Yilan County", "Hualien County", "Taitung City", "Penghu County", "Kinmen County", "Lienchiang County"];
var cityobject = [];
$("#dropdown").empty();

/*
Get value from Bootstrap dropdown menu
*/

$.each(citiesChinese, function(index, element) {
        //console.log(cities[index]);
  url ="https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22"+citiesEnglish[index]+"\")%20and%20u%3D'C'&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys";
  $.getJSON(url, function(data) {
    var currentTemperature = data.query.results.channel.item.condition.temp;
       //   list.children('a').html(list.text()+" "+currentTemperature + "℃");
       list.children('a').html(list.text()+""+"<span style=\"float:right; margin-right:px;\">"+currentTemperature + "℃"+"</span>" );
       cityobject[index]= {data ,"object" : citiesChinese[index]};
       if( cityobject[index].object === "臺北市"){
        displayWeather("Taipei City");
      }
    });
  var list = $("<li role=\"presentation\"><a role=\"menuitem\" tabindex=\"-1\" href=\"#\">" + citiesChinese[index] +"</a></li>");
  list.appendTo("#dropdown");

});
$('#dropdown li a').on('click', function() {
  var city=$(this).text().slice(0,$(this).text().length-3);
  for(var i=0 ; i < cityobject.length;i++){
    if(city === cityobject[i].object){
     console.log(citiesChinese[i]+" "+citiesEnglish[i]);
      displayWeather(citiesEnglish[i]);
      $(".btn-default").text($(this).text());
    }
  }
});

function displayWeather(place)
{
 // console.log (place) ;
  var url ="https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22"+place+"\")%20and%20u%3D'C'&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys";
  $.getJSON(url
    ,function(data){
  //  console.log (data) ; // 可以比較方便你找到你要的資料在這個物件的哪個位置
    var currentTemperature = data.query.results.channel.item.condition.temp; // 就可以找到現在溫度
    var currentDate = data.query.results.channel.item.forecast[0].date;
    var currentText = data.query.results.channel.item.condition.text;
   // console.log (currentTemperature) ; 
   // console.log (currentDate) ; 
  //  console.log (currentText) ; 
    skycons.set("today",  WeatherIcon(currentText));
    var color = WeatherColor(WeatherIcon(currentText));
    document.body.style.backgroundColor = color;
 //   console.log (currentText+" "+WeatherIcon(currentText)) ; 
    $(".temperature").html(currentTemperature);
    $(".condition .date").html(currentDate);
    $(".condition .text").html(currentText);
    //明天天氣預報
    var firsthigh = data.query.results.channel.item.forecast[1].high;
    var firstlow  = data.query.results.channel.item.forecast[1].low;
    var firstDate = data.query.results.channel.item.forecast[1].date;
    var firstText = data.query.results.channel.item.forecast[1].text;
  //  console.log (firsthigh) ; 
  //  console.log (firstDate) ; 
  //  console.log (firstText) ; 
    skycons.set("day1",  WeatherIcon(firstText));
    var color = WeatherColor(WeatherIcon(firstText));
    $(".table tr:nth-child(2) td:nth-child(1)").css("backgroundColor",color);
    $(".table tbody tr:nth-child(1) td:nth-child(1)").html(firstlow+" - "+firsthigh+"&#8451;");
    $(".table thead tr:nth-child(1) th:nth-child(1)").html(firstDate);
    //$(".table tbody tr:nth-child(2) td:nth-child(1)").html(firstText);
    //後天天氣預報
    var Secondhigh = data.query.results.channel.item.forecast[2].high;
    var Secondlow  = data.query.results.channel.item.forecast[2].low;
    var SecondDate = data.query.results.channel.item.forecast[2].date;
    var SecondText = data.query.results.channel.item.forecast[2].text;
  //  console.log (firsthigh) ; 
  //  console.log (firstDate) ; 
  //  console.log (SecondText) ; 
    skycons.set("day2",  WeatherIcon(SecondText));
    var color = WeatherColor(WeatherIcon(SecondText));
    $(".table tr:nth-child(2) td:nth-child(2)").css("backgroundColor",color);
    $(".table tbody tr:nth-child(1) td:nth-child(2)").html(Secondlow+" - "+Secondhigh+"&#8451;");
    $(".table thead tr:nth-child(1) th:nth-child(2)").html(SecondDate);
      //大後天天氣預報
    var Thirdhigh = data.query.results.channel.item.forecast[3].high;
    var Thirdlow  = data.query.results.channel.item.forecast[3].low;
    var ThirdDate = data.query.results.channel.item.forecast[3].date;
    var ThirdText = data.query.results.channel.item.forecast[3].text;
  //  console.log (firsthigh) ; 
  //  console.log (firstDate) ; 
  //  console.log (ThirdText) ; 
    skycons.set("day3",  WeatherIcon(ThirdText));
    var color = WeatherColor(WeatherIcon(ThirdText));
    $(".table tr:nth-child(2) td:nth-child(3)").css("backgroundColor",color);
    $(".table tbody tr:nth-child(1) td:nth-child(3)").html(Thirdlow+" - "+Thirdhigh+"&#8451;");
    $(".table thead tr:nth-child(1) th:nth-child(3)").html(ThirdDate);
    console.log (currentText+", "+firstText+", "+SecondText+", "+ThirdText) ; 
  });
}          

function WeatherIcon(name)
{
  if  (name==="Sunny" || name==="Fair (Day)" || name==="Hot"|| name==="Clear")
    return Skycons.CLEAR_DAY;
  else if (name==="Clear (Night)" || name==="Fair (Night)" ||name==="Mostly Clear")
    return Skycons.CLEAR_NIGHT;
  else if (name==="Mostly Cloudy (Day)" || name==="Partly Cloudy (Day)"|| name==="Partly Cloudy")
      return Skycons.PARTLY_CLOUDY_DAY;
  else if(name==="Mostly Cloudy (Night)" || name==="Partly Cloudy (Night)")
    return Skycons.PARTLY_CLOUDY_NIGHT;
  else if (name==="Haze" || name==="Smoky" || name==="Cloudy"  || name==="Mostly Cloudy")
    return Skycons.CLOUDY;
  else if (name==="Rain" || name==="Severe Thunderstorms" || name==="Thunderstorms" || name==="Freezing Drizzle" || name==="Drizzle" || name==="Freezing Rain" || name==="Showers" || name==="Mixed Rain And Hail" || name==="Isolated Thunderstorms" || name==="Scattered Thunderstorms" || name==="Scattered Showers" || name==="Thundershowers" || name==="Isolated Thundershowers")
    return Skycons.RAIN;
  else if (name==="Mixed Rain And Sleet" || name==="Sleet")
    return Skycons.SLEET;
  else if (name==="Mixed Rain And Snow" || name==="Mixed Snow And Sleet" || name==="Snow Flurries" || name==="Light Snow Showers" || name==="Blowing Snow" || name==="Snow" || name==="Hail" || name==="Heavy Snow" || name==="Scattered Snow Showers" || name==="Snow Showers")
    return Skycons.SNOW;
  else if (name==="Tornado" || name==="Tropical Storm" || name==="Hurricane" || name==="Dust" || name==="Blustery" || name==="Windy" || name==="Cold" || name==="Breezy")
    return Skycons.WIND;
  else if (name==="Foggy")
    return Skycons.FOG;
  else
    return Skycons.CLEAR_DAY;
}  
function WeatherColor(name)
{
  if  (name===Skycons.CLEAR_DAY)
    return "#FFDEA1";
  else if (name===Skycons.CLEAR_NIGHT)
    return "#F2FFFF";
  else if (name===Skycons.PARTLY_CLOUDY_DAY)
    return "#BFFFFF";
  else if(name===Skycons.PARTLY_CLOUDY_NIGHT)
    return "#DEDEDE";
  else if (name===Skycons.CLOUDY)
    return "#DEDEDE";
  else if (name===Skycons.RAIN)
    return "#E0E0FF";
  else if (name===Skycons.SLEET)
    return "#D9D9D9";
  else if (name===Skycons.SNOW)
    return "#FAF2FF";
  else if (name===Skycons.WIND)
    return "#E8C9FF";
  else if (name===Skycons.FOG)
    return "#9C9C9C";
  else
    return "#DEDEDE";
}  